DROP DATABASE GER_COMISSAO;
GO
CREATE DATABASE GER_COMISSAO;
GO
USE GER_COMISSAO;
GO

-- CREATE TABLE
CREATE TABLE VENDEDOR (
	ID SMALLINT NOT NULL,
	NOME VARCHAR(50)
);

CREATE TABLE VENDA (
	ID BIGINT NOT NULL,
	NUMERO_VENDA INT NOT NULL,
	DATAV DATE,
	HORARIO TIME,
	COMISSAO NUMERIC(4,2),
	ID_VENDEDOR SMALLINT NOT NULL
);

CREATE TABLE ITEM (
	ID INT NOT NULL,
	DESCRICAO VARCHAR(50),
	UNIDADE CHAR(3),
	PRECO NUMERIC(18,2)
);

CREATE TABLE VENDA_ITEM (
	ID INT NOT NULL,
	ID_VENDA BIGINT NOT NULL,
	ID_ITEM INT NOT NULL,
	PRECO NUMERIC(18,2),
	QUANTIDADE NUMERIC(18,2)
);

-- PKS
ALTER TABLE VENDEDOR
	ADD CONSTRAINT PK_VENDEDOR
		PRIMARY KEY (ID);
ALTER TABLE VENDA
	ADD CONSTRAINT PK_VENDA
		PRIMARY KEY (ID);
ALTER TABLE ITEM
	ADD CONSTRAINT PK_ITEM
		PRIMARY KEY (ID);
ALTER TABLE VENDA_ITEM
	ADD CONSTRAINT PK_VENDA_ITEM
		PRIMARY KEY (ID);

-- FK
ALTER TABLE VENDA 
	ADD CONSTRAINT FK_VENDEDOR_VENDA
		FOREIGN KEY (ID_VENDEDOR)
			REFERENCES VENDEDOR (ID);
ALTER TABLE VENDA_ITEM
	ADD CONSTRAINT FK_VENDA_VENDA_ITEM
		FOREIGN KEY (ID_VENDA)
			REFERENCES VENDA (ID);
ALTER TABLE VENDA_ITEM
	ADD CONSTRAINT FK_ITEM_VENDA_ITEM
		FOREIGN KEY (ID_ITEM)
			REFERENCES ITEM (ID);

-- deletar constraint
-- ALTER TABLE VENDA_ITEM 
--	DROP CONSTRAINT FK_VENDEDOR_VENDA;

-- INSERIR REGISTROS
SELECT * FROM VENDEDOR;
-- insert
INSERT INTO VENDEDOR (ID, NOME)
	VALUES
		(1, 'Bruno Bevilaqua'),
		(2, 'Machado de Assis');

--update
UPDATE VENDEDOR 
	SET NOME = 'Bruno Fernando Bevilaqua'
WHERE id = 1;

-- delete
DELETE FROM VENDEDOR 
	WHERE ID = 1;

SET DATEFORMAT DMY;

SELECT * FROM VENDA;
INSERT INTO VENDA(ID, NUMERO_VENDA, DATAV, HORARIO, COMISSAO, ID_VENDEDOR) 
	VALUES
		(2, 1333, '15.11.2021','22:56', 1, 2);

-- JOIN
SELECT 
	VE.ID, VE.DATAV, VV.NOME
FROM VENDA VE
INNER JOIN VENDEDOR VV ON VE.ID = VV.ID;

SELECT * FROM ITEM;
INSERT INTO ITEM (ID, DESCRICAO, UNIDADE, PRECO)
VALUES
	(1, 'Feijão', 'KLG', 5.55),
	(2, 'Arroz', 'KLG', 4.30),
	(3, 'Ovo', 'DUZ', 10.99);


SELECT * FROM VENDA_ITEM;
INSERT INTO VENDA_ITEM (ID, ID_ITEM, ID_VENDA, QUANTIDADE, PRECO)
VALUES
	(1, 1, 1, 5.55, 3),
	(2, 3, 1, 4.55, 6.55),
	(3, 2, 1, 10, 4);

SELECT VI.ID_ITEM, VI.ID_VENDA, V.HORARIO, I.DESCRICAO, VI.PRECO, I.UNIDADE, VD.NOME, VI.QUANTIDADE,
(VI.QUANTIDADE * VI.PRECO)*(V.COMISSAO / 100)  AS COMISSAO, (VI.QUANTIDADE * VI.PRECO) AS TOTAL_VENDA
FROM VENDA V
	INNER JOIN VENDA_ITEM VI ON VI.ID_VENDA = V.ID
	INNER JOIN ITEM I ON I.ID = VI.ID_ITEM
	INNER JOIN VENDEDOR VD ON VD.ID = V.ID_VENDEDOR;